import type { IncomingMessage } from "node:http";
import type { WebSocket } from "ws";

/** appName values are generated by Nixploy (service names) — never trust client input into a shell/docker filter without this check. */
const APP_NAME_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,127}$/;

export function isValidAppName(appName: string): boolean {
	return APP_NAME_PATTERN.test(appName);
}

/** Convert Node upgrade-request headers into a Fetch `Headers` instance for better-auth. */
export function requestHeaders(req: IncomingMessage): Headers {
	const headers = new Headers();
	for (const [key, value] of Object.entries(req.headers)) {
		if (value === undefined) continue;
		headers.set(key, Array.isArray(value) ? value.join(", ") : value);
	}
	return headers;
}

/** Parse the query string of an upgrade request. */
export function upgradeSearchParams(req: IncomingMessage): URLSearchParams {
	return new URL(req.url ?? "/", "http://localhost").searchParams;
}

/** Backpressure-aware send: drops the socket if the client falls too far behind instead of growing memory unbounded. */
const MAX_BUFFERED_BYTES = 8 * 1024 * 1024;

export function safeSend(ws: WebSocket, data: string | Buffer): boolean {
	if (ws.readyState !== ws.OPEN) return false;
	if (ws.bufferedAmount > MAX_BUFFERED_BYTES) {
		ws.terminate();
		return false;
	}
	ws.send(data);
	return true;
}

/** Send a JSON frame. */
export function sendJson(ws: WebSocket, payload: unknown): boolean {
	return safeSend(ws, JSON.stringify(payload));
}

/** Close with an application-level error the UI can surface. */
export function closeWithError(ws: WebSocket, message: string): void {
	sendJson(ws, { type: "error", message });
	ws.close(1008, message.slice(0, 120));
}
