/**
 * The catalog's category vocabulary, and how a source's free-form tags map
 * onto it.
 *
 * A blueprint declares tags, not a category, and the first one used to become
 * the category verbatim. On the public blueprints catalog that produced **209
 * categories for 436 templates, 125 of them holding a single entry** —
 * "File-manager", "Whatsapp", "Erp" — which is not a filter, it is a list of
 * templates spelled differently. The gallery's category rail was unusable and
 * so was the landing catalog's grouping.
 *
 * So tags are resolved against the fifteen categories the built-in catalog
 * already uses. The tag list is read in order and the first tag that maps
 * wins, which is why the map deliberately does NOT contain the generic tags
 * every entry carries (`self-hosted`, `open-source`, `web`, `app`): they would
 * swallow everything they precede. Nothing recognizable falls through to
 * `Community`, which stays visible rather than being hidden inside a real
 * category.
 */

/** What `catalog.ts` labels the built-in templates with. */
export const TEMPLATE_CATEGORIES = [
	"AI",
	"Analytics",
	"Apps",
	"CMS",
	"Communication",
	"Databases",
	"Developer Tools",
	"Finance",
	"Knowledge",
	"Media",
	"Monitoring",
	"Notifications",
	"Productivity",
	"Security",
	"Storage",
] as const;

export type TemplateCategory = (typeof TEMPLATE_CATEGORIES)[number];

/** Where an unrecognized entry lands. */
export const FALLBACK_CATEGORY = "Community";

/**
 * Tag → category. Lowercase keys; a tag is also matched after `_` and spaces
 * are turned into `-`, so `file_manager` and `file manager` reach
 * `file-manager`.
 */
const TAG_CATEGORY: Record<string, TemplateCategory> = {
	// AI
	ai: "AI",
	llm: "AI",
	llms: "AI",
	chatbot: "AI",
	chatbots: "AI",
	"machine-learning": "AI",
	ml: "AI",
	rag: "AI",
	agents: "AI",
	"ai-agents": "AI",
	openai: "AI",
	gpt: "AI",
	ollama: "AI",
	"stable-diffusion": "AI",
	"image-generation": "AI",
	tts: "AI",
	stt: "AI",
	"speech-to-text": "AI",
	"text-to-speech": "AI",
	embeddings: "AI",
	"vector-search": "AI",
	nlp: "AI",
	"computer-vision": "AI",

	// Analytics
	analytics: "Analytics",
	"web-analytics": "Analytics",
	"product-analytics": "Analytics",
	telemetry: "Analytics",
	statistics: "Analytics",
	stats: "Analytics",
	"business-intelligence": "Analytics",
	bi: "Analytics",
	tracking: "Analytics",
	"ab-testing": "Analytics",
	"feature-flags": "Analytics",

	// Databases
	database: "Databases",
	databases: "Databases",
	db: "Databases",
	sql: "Databases",
	nosql: "Databases",
	postgres: "Databases",
	postgresql: "Databases",
	mysql: "Databases",
	mariadb: "Databases",
	sqlite: "Databases",
	redis: "Databases",
	valkey: "Databases",
	mongodb: "Databases",
	mongo: "Databases",
	clickhouse: "Databases",
	cassandra: "Databases",
	elasticsearch: "Databases",
	opensearch: "Databases",
	"time-series": "Databases",
	timeseries: "Databases",
	"vector-database": "Databases",
	"graph-database": "Databases",
	"key-value": "Databases",

	// Monitoring
	monitoring: "Monitoring",
	observability: "Monitoring",
	metrics: "Monitoring",
	logging: "Monitoring",
	logs: "Monitoring",
	uptime: "Monitoring",
	"uptime-monitoring": "Monitoring",
	"status-page": "Monitoring",
	statuspage: "Monitoring",
	alerting: "Monitoring",
	apm: "Monitoring",
	tracing: "Monitoring",
	"error-tracking": "Monitoring",
	"health-check": "Monitoring",
	"health-checks": "Monitoring",

	// Media
	torrents: "Media",
	subtitles: "Media",
	sonarr: "Media",
	radarr: "Media",
	deluge: "Media",
	"3d": "Media",
	rendering: "Media",
	animation: "Media",
	"image-editing": "Media",
	media: "Media",
	video: "Media",
	audio: "Media",
	music: "Media",
	streaming: "Media",
	photos: "Media",
	photo: "Media",
	gallery: "Media",
	podcast: "Media",
	podcasts: "Media",
	movies: "Media",
	tv: "Media",
	"media-server": "Media",
	transcoding: "Media",
	downloader: "Media",
	torrent: "Media",
	"live-streaming": "Media",
	ebooks: "Media",
	audiobooks: "Media",
	comics: "Media",

	// CMS
	cms: "CMS",
	"content-management": "CMS",
	blog: "CMS",
	blogging: "CMS",
	website: "CMS",
	"site-builder": "CMS",
	"website-builder": "CMS",
	"static-site": "CMS",
	ecommerce: "CMS",
	"e-commerce": "CMS",
	shop: "CMS",
	store: "CMS",
	storefront: "CMS",
	headless: "CMS",
	portfolio: "CMS",
	landing: "CMS",

	// Knowledge
	notes: "Knowledge",
	"note-taking": "Knowledge",
	wiki: "Knowledge",
	documentation: "Knowledge",
	docs: "Knowledge",
	"knowledge-base": "Knowledge",
	markdown: "Knowledge",
	bookmarks: "Knowledge",
	bookmarking: "Knowledge",
	"read-it-later": "Knowledge",
	rss: "Knowledge",
	"feed-reader": "Knowledge",
	reader: "Knowledge",
	library: "Knowledge",
	recipes: "Knowledge",
	"second-brain": "Knowledge",
	flashcards: "Knowledge",

	// Productivity
	"task-tracking": "Productivity",
	"document-signing": "Productivity",
	drawing: "Productivity",
	diagrams: "Productivity",
	whiteboarding: "Productivity",
	feedback: "Productivity",
	roadmap: "Productivity",
	"q-and-a": "Productivity",
	"asset-tracking": "Productivity",
	productivity: "Productivity",
	"project-management": "Productivity",
	tasks: "Productivity",
	"task-management": "Productivity",
	todo: "Productivity",
	kanban: "Productivity",
	calendar: "Productivity",
	scheduling: "Productivity",
	"time-tracking": "Productivity",
	workflow: "Productivity",
	workflows: "Productivity",
	automation: "Productivity",
	"low-code": "Productivity",
	"no-code": "Productivity",
	forms: "Productivity",
	survey: "Productivity",
	surveys: "Productivity",
	whiteboard: "Productivity",
	collaboration: "Productivity",
	crm: "Productivity",
	helpdesk: "Productivity",
	ticketing: "Productivity",
	"customer-support": "Productivity",

	// Communication
	chat: "Communication",
	messaging: "Communication",
	communication: "Communication",
	email: "Communication",
	mail: "Communication",
	smtp: "Communication",
	newsletter: "Communication",
	forum: "Communication",
	forums: "Communication",
	social: "Communication",
	"social-network": "Communication",
	fediverse: "Communication",
	matrix: "Communication",
	irc: "Communication",
	voip: "Communication",
	"video-conferencing": "Communication",
	"video-calls": "Communication",
	whatsapp: "Communication",
	telegram: "Communication",
	discord: "Communication",
	sms: "Communication",

	// Notifications
	notifications: "Notifications",
	notification: "Notifications",
	alerts: "Notifications",
	push: "Notifications",
	"push-notifications": "Notifications",

	// Finance
	finance: "Finance",
	accounting: "Finance",
	budgeting: "Finance",
	budget: "Finance",
	invoicing: "Finance",
	invoices: "Finance",
	billing: "Finance",
	payments: "Finance",
	banking: "Finance",
	crypto: "Finance",
	cryptocurrency: "Finance",
	trading: "Finance",
	expenses: "Finance",
	"expense-tracking": "Finance",
	erp: "Finance",
	pos: "Finance",

	// Security
	"role-based-access": "Security",
	security: "Security",
	authentication: "Security",
	auth: "Security",
	sso: "Security",
	oauth: "Security",
	identity: "Security",
	iam: "Security",
	password: "Security",
	passwords: "Security",
	"password-manager": "Security",
	secrets: "Security",
	"secret-management": "Security",
	vault: "Security",
	privacy: "Security",
	vpn: "Security",
	wireguard: "Security",
	firewall: "Security",
	waf: "Security",
	antivirus: "Security",
	adblock: "Security",
	"ad-blocker": "Security",
	"2fa": "Security",
	mfa: "Security",
	pentesting: "Security",
	"vulnerability-scanner": "Security",

	// Storage
	"file-storage": "Storage",
	"file-management": "Storage",
	"image-hosting": "Storage",
	sharing: "Storage",
	"document-management": "Storage",
	storage: "Storage",
	"object-storage": "Storage",
	s3: "Storage",
	backup: "Storage",
	backups: "Storage",
	"file-sharing": "Storage",
	"file-manager": "Storage",
	files: "Storage",
	"file-transfer": "Storage",
	filesystem: "Storage",
	sync: "Storage",
	"cloud-storage": "Storage",
	nas: "Storage",
	drive: "Storage",
	webdav: "Storage",
	ftp: "Storage",
	archive: "Storage",

	// Developer Tools
	crawler: "Developer Tools",
	scraping: "Developer Tools",
	i18n: "Developer Tools",
	localization: "Developer Tools",
	"bot-protection": "Developer Tools",
	visualization: "Developer Tools",
	geospatial: "Developer Tools",
	"developer-tools": "Developer Tools",
	development: "Developer Tools",
	devtools: "Developer Tools",
	devops: "Developer Tools",
	git: "Developer Tools",
	github: "Developer Tools",
	gitlab: "Developer Tools",
	ci: "Developer Tools",
	cd: "Developer Tools",
	"ci-cd": "Developer Tools",
	docker: "Developer Tools",
	kubernetes: "Developer Tools",
	containers: "Developer Tools",
	registry: "Developer Tools",
	api: "Developer Tools",
	"api-gateway": "Developer Tools",
	graphql: "Developer Tools",
	testing: "Developer Tools",
	ide: "Developer Tools",
	code: "Developer Tools",
	"code-editor": "Developer Tools",
	deployment: "Developer Tools",
	paas: "Developer Tools",
	hosting: "Developer Tools",
	server: "Developer Tools",
	proxy: "Developer Tools",
	"reverse-proxy": "Developer Tools",
	networking: "Developer Tools",
	dns: "Developer Tools",
	tunnel: "Developer Tools",
	webhook: "Developer Tools",
	webhooks: "Developer Tools",
	queue: "Developer Tools",
	"message-queue": "Developer Tools",
	cache: "Developer Tools",
	"feature-toggle": "Developer Tools",
	terminal: "Developer Tools",
	ssh: "Developer Tools",
	"self-hosting": "Developer Tools",

	// Apps — the general-purpose end of the vocabulary
	"hr-management": "Apps",
	"employee-onboarding": "Apps",
	notepad: "Apps",
	"multi-user": "Apps",
	dashboard: "Apps",
	homepage: "Apps",
	"start-page": "Apps",
	search: "Apps",
	"search-engine": "Apps",
	gaming: "Apps",
	games: "Apps",
	game: "Apps",
	"game-server": "Apps",
	"home-automation": "Apps",
	"smart-home": "Apps",
	iot: "Apps",
	health: "Apps",
	fitness: "Apps",
	education: "Apps",
	learning: "Apps",
	travel: "Apps",
	weather: "Apps",
	maps: "Apps",
	"url-shortener": "Apps",
	paste: "Apps",
	pastebin: "Apps",
	business: "Apps",
	management: "Apps",
	inventory: "Apps",
	hr: "Apps",
	marketing: "Apps",
	"event-management": "Apps",
	booking: "Apps",
	utilities: "Apps",
	tools: "Apps",
};

const normalizeTag = (tag: string): string =>
	tag
		.trim()
		.toLowerCase()
		.replace(/[\s_]+/g, "-")
		.replace(/^#/, "");

/**
 * The category for a set of source tags: the first tag that maps to one of
 * {@link TEMPLATE_CATEGORIES}, else {@link FALLBACK_CATEGORY}. Order matters —
 * a template tagged `["media", "storage"]` is Media, not Storage.
 */
export function categoryFromTags(tags: readonly string[]): string {
	for (const tag of tags) {
		const mapped = TAG_CATEGORY[normalizeTag(tag)];
		if (mapped) return mapped;
	}
	return FALLBACK_CATEGORY;
}
