import {
	DATABASE_KIND_CREDENTIALS,
	DATABASE_KINDS,
	type DatabaseServiceKind,
	SERVICE_KIND_ID_FIELDS,
} from "@nixploy/server/modules/services/kinds";
import type { TRPCOptionsProxy } from "@trpc/tanstack-react-query";
import type { LucideIcon } from "lucide-react";

import { SERVICE_TYPE_META } from "@/components/projects/service-types";
import type { AppRouter } from "@/lib/trpc-types";

/**
 * The five one-click engines, their id field and which credential inputs each
 * one actually has, all derived from the server's service registry
 * (`@nixploy/server/modules/services/kinds`). Adding an engine there makes it
 * appear here — and the compiler flags anything still missing.
 */
export type DatabaseType = DatabaseServiceKind;

/** Database types supported by the `backup` router (all five engines). */
export type BackupDatabaseType = DatabaseType;

export type ServiceStatus = "idle" | "running" | "done" | "error";

export interface DatabaseTypeConfig {
	/** Key used for the id in procedure inputs (e.g. `"postgresId"`). */
	idField: string;
	label: string;
	icon: LucideIcon;
	iconClassName: string;
	supportsBackups: boolean;
	hasDatabaseName: boolean;
	hasUser: boolean;
	hasRootPassword: boolean;
}

export const DATABASE_TYPES: Record<DatabaseType, DatabaseTypeConfig> = Object.fromEntries(
	DATABASE_KINDS.map((kind) => {
		const credentials = DATABASE_KIND_CREDENTIALS[kind];
		return [
			kind,
			{
				idField: SERVICE_KIND_ID_FIELDS[kind],
				...SERVICE_TYPE_META[kind],
				// Every engine has a dump/restore command in DB_DUMP_CONFIG.
				supportsBackups: true,
				hasDatabaseName: credentials.databaseName !== null,
				hasUser: credentials.databaseUser !== null,
				hasRootPassword: credentials.rootPassword,
			},
		];
	}),
) as Record<DatabaseType, DatabaseTypeConfig>;

export { SERVICE_TYPE_META };

/** Normalized shape shared by all five database rows (optional per-type fields). */
export interface DatabaseRow {
	name: string;
	appName: string;
	description: string | null;
	env: string | null;
	status: ServiceStatus;
	dockerImage: string;
	databaseName?: string;
	databaseUser?: string;
	databasePassword?: string;
	databaseRootPassword?: string;
	externalPort: number | null;
	serverId: string | null;
	createdAt: string;
}

/**
 * Common facade over `trpc.postgres | mysql | mariadb | mongo | redis`.
 *
 * All five routers are generated by the same `buildDatabaseRouter` factory in
 * `@nixploy/server`, so their procedure surface is identical apart from the id
 * key in each input. `postgres` therefore stands in for the shape of all five
 * and gives the panel real query/mutation option types instead of the `any`s
 * this used to carry (code-health F6). `DatabaseDetail` casts `trpc[kind]` to
 * it once, at the single dynamic-dispatch boundary.
 */
export type DatabaseRouterFacade = TRPCOptionsProxy<AppRouter>["postgres"];

/**
 * Keyed id input for database procedures. At runtime the key is the engine's
 * own (`{ mysqlId }`, `{ redisId }`, …); in the facade's terms it is always
 * the postgres one. Build it with `databaseIdInput` so the registry stays the
 * only source of the field name.
 */
export type DatabaseIdInput = { postgresId: string };

/** `{ <kind>Id: id }`, typed as the facade expects it. */
export function databaseIdInput(kind: DatabaseType, id: string): DatabaseIdInput {
	return { [SERVICE_KIND_ID_FIELDS[kind]]: id } as DatabaseIdInput;
}

export interface ConnectionUrls {
	internal: string;
	external: string | null;
}
